kind: Service
apiVersion: v1
metadata:
  name: coffee-shop-db
spec:
  selector:
    app: coffee-shop-db
  ports:
    - port: 5432
      name: postgres
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop-db
    spec:
      containers:
      - name: coffee-shop-db
        image: docker.sebastian-daschner.com/coffee-shop-db:1
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
