kind: Service
apiVersion: v1
metadata:
  name: coffee-shop-db
spec:
  selector:
    app: coffee-shop-db
  ports:
    - port: 5432
      name: postgres
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coffee-shop-db
    spec:
      containers:
      - name: coffee-shop-db
        image: docker.sebastian-daschner.com/coffee-shop-db:1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: coffee-shop-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: coffee-shop-db-data
        persistentVolumeClaim:
          claimName: coffee-shop-db-vc
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coffee-shop-db-vc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
  selector:
    matchLabels:
      storage: coffee-shop-db
